import type { Lang } from "./i18n";

/**
 * Los rótulos de las pantallas de producto. Se traducen igual que el resto:
 * una página en inglés con la interfaz en castellano se lee como un descuido,
 * aunque el sistema real esté en castellano.
 */
const ES = {
  genesis: "Génesis · Inventario",
  comprobantes: "Comprobantes · Cola",
  skus: "SKUs activos",
  stockBajo: "Stock bajo",
  rotacion: "Rotación",
  procesadas: "Procesadas",
  aRevisar: "A revisar",
  operacion: "Operación",
  analisis: "Análisis",
  menu: ["Tablero", "Pedidos", "Recepciones", "Catálogo"],
  menu2: ["Rotación", "Proveedores"],
  admin: "Administrador",
  tablero: "Tablero de operación",
  sincronia: "Última sincronía 09:41",
  exportar: "Exportar CSV",
  nuevoPedido: "Nuevo pedido",
  skusNota: "13 tablas · 4 sectores",
  reorden: "Bajo punto de reorden",
  reordenNota: "Umbral configurable",
  capital: "Capital inmovilizado",
  capitalNota: "A precio de proveedor",
  rotacionMes: "Rotación mensual",
  rotacionNota: "Promedio 12 meses",
  movimiento: "Movimiento por SKU",
  orden: "Ordenado por rotación ↓",
  cols: ["SKU", "Producto", "Stock", "Reserva", "Estado"],
  ok: "OK",
  reponer: "Reponer",
  alertas: "Alertas activas",
  productos: [
    "Taza sublimable 11oz — blanca",
    "Remera algodón peinado — M",
    "Vaso térmico acero 500ml",
    "Gorra bordada — negra",
    "Mousepad sublimable XL",
  ],
  avisos: [
    { texto: "Remera algodón peinado — M por debajo del reorden", meta: "Hace 2 h · Sector textil" },
    { texto: "Mousepad sublimable XL con 2 pedidos en espera", meta: "Hace 5 h · Sector sublimación" },
    { texto: "Precio de proveedor desactualizado hace 34 días", meta: "Ayer · 3 proveedores" },
  ],
  documento: "Documento recibido",
  campos: "Campos extraídos",
  camposNota: "11 de 11 · 1,8 s",
  cola: "Cola del día",
  registrada: "Registrada",
  revisar: "A revisar",
  porRegla: "Por regla",
  rotulos: {
    empresa: "Empresa", comprobante: "N° de comprobante", fecha: "Fecha de emisión",
    tipo: "Tipo", iva: "IVA", percepciones: "Percepciones", moneda: "Moneda", cambio: "Tipo de cambio",
    cae: "CAE", subtotal: "Subtotal", ivaPct: "IVA 21%", iibb: "Percep. IIBB", total: "Total",
  },
  reglaAviso: "El comprobante no traía CAE, pero el número contiene «-A»: se clasificó como Factura A por regla y queda marcado para revisión.",
  reglaMeta: "Regla fiscal 04 · Aplicada automáticamente",
};

const EN: typeof ES = {
  genesis: "Génesis · Inventory",
  comprobantes: "Invoices · Queue",
  skus: "Active SKUs",
  stockBajo: "Low stock",
  rotacion: "Turnover",
  procesadas: "Processed",
  aRevisar: "To review",
  operacion: "Operations",
  analisis: "Analysis",
  menu: ["Dashboard", "Orders", "Receiving", "Catalogue"],
  menu2: ["Turnover", "Suppliers"],
  admin: "Administrator",
  tablero: "Operations dashboard",
  sincronia: "Last sync 09:41",
  exportar: "Export CSV",
  nuevoPedido: "New order",
  skusNota: "13 tables · 4 areas",
  reorden: "Below reorder point",
  reordenNota: "Configurable threshold",
  capital: "Capital tied up",
  capitalNota: "At supplier cost",
  rotacionMes: "Monthly turnover",
  rotacionNota: "12-month average",
  movimiento: "Movement by SKU",
  orden: "Sorted by turnover ↓",
  cols: ["SKU", "Product", "Stock", "Reserved", "Status"],
  ok: "OK",
  reponer: "Restock",
  alertas: "Active alerts",
  productos: [
    "Sublimation mug 11oz — white",
    "Combed cotton tee — M",
    "Steel thermal bottle 500ml",
    "Embroidered cap — black",
    "Sublimation mousepad XL",
  ],
  avisos: [
    { texto: "Combed cotton tee — M below reorder point", meta: "2 h ago · Textile area" },
    { texto: "Sublimation mousepad XL with 2 orders waiting", meta: "5 h ago · Sublimation area" },
    { texto: "Supplier price 34 days out of date", meta: "Yesterday · 3 suppliers" },
  ],
  documento: "Document received",
  campos: "Extracted fields",
  camposNota: "11 of 11 · 1.8 s",
  cola: "Today's queue",
  registrada: "Recorded",
  revisar: "To review",
  porRegla: "By rule",
  rotulos: {
    empresa: "Company", comprobante: "Invoice number", fecha: "Issue date",
    tipo: "Type", iva: "VAT", percepciones: "Withholdings", moneda: "Currency", cambio: "Exchange rate",
    cae: "Tax code", subtotal: "Subtotal", ivaPct: "VAT 21%", iibb: "Gross income w/h", total: "Total",
  },
  reglaAviso: "The document had no tax authorisation code, but the number contains «-A»: it was classified as an A-type invoice by rule and flagged for review.",
  reglaMeta: "Tax rule 04 · Applied automatically",
};

export function rotulos(lang: Lang) {
  return lang === "en" ? EN : ES;
}
